apiVersion: v1
kind: Service
metadata:
  name: {{ include "requestmanagement.fullname" . }}
  labels:
    {{- include "requestmanagement.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "requestmanagement.selectorLabels" . | nindent 4 }} 