apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semanix-backend-accessmanagement
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: accessmanagementapi=samthedonz.azurecr.io/accessmanagementapi
    argocd-image-updater.argoproj.io/accessmanagementapi.update-strategy: semver
    argocd-image-updater.argoproj.io/accessmanagementapi.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
spec:
  project: default
  source:
    repoURL: "samthedonz.azurecr.io/helm"   # << Note oci:// here
    targetRevision: "0.2.1"                     # << This is your Helm chart version (the tag)
    chart: accessmanagement
    helm:                               # << Required for OCI support
      parameters:
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "semanix-backend-accessmanagement"
        - name: image.repository
          value: "samthedonz.azurecr.io/accessmanagementapi"
        - name: image.tag
          value: ""
      values: |
        dapr:
          enabled: true
          appId: accessmanagement
          appPort: 8080
          config: dapr-config
  destination:
    server: https://kubernetes.default.svc
    namespace: semanix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
