apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semanix-backend-requestmanagement
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: requestmanagementapi=samthedonz.azurecr.io/requestmanagementapi
    argocd-image-updater.argoproj.io/requestmanagementapi.update-strategy: semver
    argocd-image-updater.argoproj.io/requestmanagementapi.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
spec:
  project: default
  source:
    repoURL: "samthedonz.azurecr.io/helm"
    targetRevision: "0.1.10"
    chart: requestmanagement
    helm: 
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "semanix-backend-requestmanagement"
        - name: image.repository
          value: "samthedonz.azurecr.io/requestmanagementapi"
        - name: image.tag
          value: "0.2.11"
      values: |
        dapr:
          enabled: true
          appId: requestmanagement
          appPort: 8080
          config: dapr-config
  destination:
    server: https://kubernetes.default.svc
    namespace: semanix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
