apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semanix-backend-requestmanagement
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: requestmanagementapi=samthedonz.azurecr.io/requestmanagementapi
    argocd-image-updater.argoproj.io/requestmanagementapi.update-strategy: digest
    argocd-image-updater.argoproj.io/requestmanagementapi.allow-tags: regexp:^[a-f0-9]{7}$
spec:
  project: default
  source:
    repoURL: "samthedonz.azurecr.io/helm"
    targetRevision: "0.1.4"
    chart: requestmanagement
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "semanix-backend-requestmanagement"
        - name: image.repository
          value: "samthedonz.azurecr.io/requestmanagementapi"
        - name: image.tag
          value: "a9672eb"
      values: |
        dapr:
          enabled: true
          appId: requestmanagement
          appPort: 8080
          config: dapr-config
  destination:
    server: https://kubernetes.default.svc
    namespace: semanix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
