name: Helm Charts Update

on:
  push:
    branches: [main]
    paths:
      - 'helm/charts/**'
      - 'k8s/argocd/**'

env:
  AZURE_REGISTRY_HELM_PATH: helm

jobs:
  push-all-charts:
    runs-on: [self-hosted, azure]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.11.0'

    - name: Login to Helm OCI Registry
      run: |
        helm registry login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io \
          --username ${{ secrets.AZURE_REGISTRY_USERNAME }} \
          --password ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Package and Push All Charts
      run: |
        mkdir -p ./deploy/helm/releases
        
        # Loop through all chart folders
        for dir in helm/charts/*/
        do
          echo "Processing chart in directory: $dir"
          
          # Read chart name
          chart_name=$(basename "$dir")
          
          # Read chart version
          chart_version=$(grep '^version:' "$dir/Chart.yaml" | awk '{print $2}')
          
          echo "Chart Name: $chart_name, Version: $chart_version"
          
          # Package the chart
          helm package "$dir" -d ./deploy/helm/releases
          
          # Push the chart
          helm push ./deploy/helm/releases/${chart_name}-${chart_version}.tgz \
            oci://${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ env.AZURE_REGISTRY_HELM_PATH }}
        done
